sudo: false
dist: trusty
language: rust
cache:
  directories:
    - $HOME/.cargo

rust:
  - nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_script:
  # install dependencies
  - cargo install --list | grep clippy || cargo install clippy
  - cargo install --list | grep rustfmt || cargo install rustfmt
  - cargo install --list | grep cargo-update || cargo install cargo-update

  # install updates
  - cargo install-update -a

script:
  # linting
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose


after_success: |
  wget -O kcov.tar.gz https://rschmidmeister.nyc3.digitaloceanspaces.com/binaries/kcov/kcov-x86_64-gnu-linux.tar.gz &&
  mkdir kcov &&
  tar -xzf kcov.tar.gz -C ./kcov &&
  for file in target/debug/ink-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
